### ISSUE TITLE
[V1] WaitForTransaction not working for 1 confirmation

### ISSUE THREAD

**Issue by Roger-RumbleFish** [godwokenrises/godwoken-web3#283] opened 2022-04-14 06:48 UTC
When i make a chain of calls  example
1. Approve the ERC20 token i want to deposit
2. Deposit the ERC20 token

each call return `ContractTransaction`. i can wait for the transaction to be mined by using method `wait`
`wait` method call under the hood WaitForTransaction from ethers.
`wait` method accept number of confirmations -> 1 confirmation is 1 block
Default implementation of ethers js provider 1 confirmation. So when we call wait without parameters it should wait 1 block
![image](https://user-images.githubusercontent.com/82821191/163328790-dd752d17-c8aa-4c2c-b7f0-88d6ed6cd4d7.png)

ethers call eth_getTransactionReceipt

![image](https://user-images.githubusercontent.com/82821191/163337493-b4c55cba-b82a-43aa-aa1e-a545fb658551.png)

I wonder if Godwoken return receipt when transaction is pending? (it should return null)

![image](https://user-images.githubusercontent.com/82821191/163340014-f00e94af-efb9-4511-95b3-8cde13d8ccd0.png)

and confirmation is calculate as `currentBlockNumber on BlockChain -  blockNumber of receipt + 1`

![image](https://user-images.githubusercontent.com/82821191/163338305-89904cf4-7e02-4cd6-b134-35e6e5aeeeb5.png)

The problem is when i set it up as 1 confirmation It doesn't wait and MetaMask queue the calls which leads to crash of request number 2 because i have to approve my ERC20 token

I solved this problem by setting up confirmations to 2 but there is a drawback. Now when action is done inside MetaMask is still wait 1 block and after that i can run next method in my case deposit

on ENV blockchain 1 confirmation should wait until the transaction is mined and when MetaMask show that operation is completed we should go to next action

**Comment by Roger-RumbleFish** [comment] 2022-04-15 10:28
It seems the problem is related with MetaMask only. I made 3 calls without MetaMask with my private key 
 ```
 Minting ADA in amount 10000000000 for account 0x13c7e473F70c70369631eE99eBD89734Ece9dc06
User Balances ADA:(Before) 18000000000
User Balances ADA:(After) 28000000000
Deposit token ADA in amount 1000000000 for account 0x13c7e473F70c70369631eE99eBD89734Ece9dc06

    Balance before

ADA Balance: 28000000000
AADA Balance: 2200000000

    Balance after

ADA Balance: 27000000000
AADA Balance: 3200000000
 
Deposit completed
Done in 19.28s
```
Here is my logs. I was able to mint / approve/ deposit my tokens in 19 seconds with using standard ethers js provider with wait method that use 1 confirmation check

**Comment by RetricSu** [comment] 2022-04-20 03:59
I use https://metamask.github.io/test-dapp/ to approve and transfer erc20. the calls are sequential, after waiting like one or two minutes, both calls succeed.

I believe the problem is due to the fact that ethers.js and metamask have different confirmation mechanisms. ether.js works with the instant-finality feature in godwoken whilst Metamask seems not. If you submit one transaction in metamask, even though the tx is successful with instant-finality, metamask still waits to get the block number it wants. so the confirmation is ignoring `receipt.blockNumber`, we hack the receipt block number in instant-finality feature, but we can not hack the getBlockNumber Rpc.

this issue should be solved after we come up with some idea to make metamask work with instant-finality as well.

**Comment by RetricSu** [comment] 2022-04-20 03:59
I use https://metamask.github.io/test-dapp/ to approve and transfer erc20. the calls are sequential, after waiting like one or two minutes, both calls succeed.

I believe the problem is due to the fact that ethers.js and metamask have different confirmation mechanisms. ether.js works with the instant-finality feature in godwoken whilst Metamask seems not. If you submit one transaction in metamask, even though the tx is successful with instant-finality, metamask still waits to get the block number it wants. so the confirmation is ignoring `receipt.blockNumber`, we hack the receipt block number in instant-finality feature, but we can not hack the getBlockNumber Rpc.

this issue should be solved after we come up with some idea to make metamask work with instant-finality as well.

**Comment by RetricSu** [comment] 2022-04-21 07:27
Update: After discussion, we are considering removing the instant-finality feature and reducing the block interval time for better compatibility and UX. 

Right now I suggest going with the workaround by setting wait 2 blocks(the real cost time here is actually one block because we hack the tx'receipt blockNumber) on ethers.js to stay the same behavior with metamask for a temp solution.

**Comment by RetricSu** [comment] 2022-11-10 06:26
hi @Roger-RumbleFish we plan to add a switcher via special RPC URL params(eg: `https://web3_rpc_url?instant-finality-hack=true`) to allow developers to turn on instant-finality feature explicitly. So the default RPC is more compatible without the instant-finality. will this work for you?

related PR:
- https://github.com/godwokenrises/godwoken-web3/pull/568

**Comment by Roger-RumbleFish** [comment] 2022-11-18 09:07
I think it is a good idea. Yes it work for me to be turn off from default

**Comment by RetricSu** [comment] 2022-12-19 02:58
the feature is deployed on mainet so I am closing this issue.

**Closed by RetricSu** 2022-12-19 02:58 UTC
Labels: P-High, metamask
